### ISSUE TITLE
Library configuration issues

### ISSUE THREAD

**Issue by brkygokcen** [NVlabs/6dof-graspnet#9]
Hi, first of all thank you for sharing this work. I am currently trying to run this work but i am suffering a lot of incompatibility issues about libraries. Can you share required libraries with version tags? It will very helpfull to handle runtime errors. By the way tensorflow-gpu 1.12 is working without any problem with python 2.7 but especially mayavi library generates some issues.
My current config is:
`
vtk==8.1.2
pyrender==0.1.18 
opencv-python 
h5py 
svg.path 
shapely 
tqdm 
python-fcl==0.0.12
pyyaml 
easydict 
PySide==1.2.4
mayavi==4.6.0 
rtree==0.9.4
scipy==1.2.3 
numpy==1.16.6
matplotlib==2.0.2
Pillow==6.2.0
traitsui==6.0.0
traits==4.6.0
pyface==6.0.0
Markdown==3.1.1
setuptools==44.1.1
`

 I added my last error below. Thanks in advance.
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cavy/graspnet/6dof-graspnet/demo/main.py", line 152, in <module>
    main(sys.argv[1:])
  File "/home/cavy/graspnet/6dof-graspnet/demo/main.py", line 142, in main
    grasp_scores=generated_scores,
  File "visualization_utils.py", line 107, in draw_scene
    src.add_attribute(rgba, 'colors')
AttributeError: 'VTKDataSource' object has no attribute 'add_attribute'
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x5000018
  Serial number of failed request:  60
  Current serial number in output stream:  62`

**Comment by clemense** [comment]
Hi,
This is my working pipenv dependency graph:
```
easydict==1.9
horovod==0.18.2
  - cffi [required: >=1.4.0, installed: 1.13.2]
    - pycparser [required: Any, installed: 2.19]
  - cloudpickle [required: Any, installed: 1.2.2]
  - psutil [required: Any, installed: 5.6.7]
  - pyyaml [required: Any, installed: 5.2]
  - six [required: Any, installed: 1.13.0]
mayavi==4.7.1
  - apptools [required: Any, installed: 4.5.0]
    - configobj [required: Any, installed: 5.0.6]
      - six [required: Any, installed: 1.13.0]
    - six [required: Any, installed: 1.13.0]
    - traitsui [required: Any, installed: 6.1.3]
      - pyface [required: >=6.0.0, installed: 6.1.2]
        - traits [required: Any, installed: 5.2.0]
          - six [required: Any, installed: 1.13.0]
      - six [required: Any, installed: 1.13.0]
      - traits [required: Any, installed: 5.2.0]
        - six [required: Any, installed: 1.13.0]
  - envisage [required: Any, installed: 4.9.0]
    - apptools [required: Any, installed: 4.5.0]
      - configobj [required: Any, installed: 5.0.6]
        - six [required: Any, installed: 1.13.0]
      - six [required: Any, installed: 1.13.0]
      - traitsui [required: Any, installed: 6.1.3]
        - pyface [required: >=6.0.0, installed: 6.1.2]
          - traits [required: Any, installed: 5.2.0]
            - six [required: Any, installed: 1.13.0]
        - six [required: Any, installed: 1.13.0]
        - traits [required: Any, installed: 5.2.0]
          - six [required: Any, installed: 1.13.0]
    - setuptools [required: Any, installed: 42.0.2]
    - six [required: Any, installed: 1.13.0]
    - traits [required: Any, installed: 5.2.0]
      - six [required: Any, installed: 1.13.0]
  - numpy [required: Any, installed: 1.16.5]
  - pyface [required: >=6.1.1, installed: 6.1.2]
    - traits [required: Any, installed: 5.2.0]
      - six [required: Any, installed: 1.13.0]
  - pygments [required: Any, installed: 2.5.2]
  - traits [required: >=4.6.0, installed: 5.2.0]
    - six [required: Any, installed: 1.13.0]
  - traitsui [required: >=6.0.0, installed: 6.1.3]
    - pyface [required: >=6.0.0, installed: 6.1.2]
      - traits [required: Any, installed: 5.2.0]
        - six [required: Any, installed: 1.13.0]
    - six [required: Any, installed: 1.13.0]
    - traits [required: Any, installed: 5.2.0]
      - six [required: Any, installed: 1.13.0]
  - vtk [required: Any, installed: 8.1.2]
numpy-quaternion==2019.12.11.22.25.52
  - numpy [required: >=1.13, installed: 1.16.5]
opencv-python==4.1.2.30
  - numpy [required: >=1.11.1, installed: 1.16.5]
pyrender==0.1.18
  - freetype-py [required: Any, installed: 2.1.0.post1]
  - imageio [required: Any, installed: 2.6.1]
    - enum34 [required: Any, installed: 1.1.6]
    - futures [required: Any, installed: 3.3.0]
    - numpy [required: Any, installed: 1.16.5]
    - pillow [required: Any, installed: 6.2.1]
  - networkx [required: ==2.2, installed: 2.2]
    - decorator [required: >=4.3.0, installed: 4.4.1]
  - numpy [required: Any, installed: 1.16.5]
  - Pillow [required: Any, installed: 6.2.1]
  - pyglet [required: ==1.4.0b1, installed: 1.4.0b1]
    - future [required: Any, installed: 0.18.2]
  - PyOpenGL [required: Any, installed: 3.1.4]
  - PyOpenGL-accelerate [required: Any, installed: 3.1.4]
  - six [required: Any, installed: 1.13.0]
  - trimesh [required: Any, installed: 3.5.4]
    - numpy [required: Any, installed: 1.16.5]
    - setuptools [required: Any, installed: 42.0.2]
PySide==1.2.4
Quaternion==0.3.1
tf-nightly-gpu==2.1.0.dev20191203
  - absl-py [required: >=0.7.0, installed: 0.8.1]
    - enum34 [required: Any, installed: 1.1.6]
    - six [required: Any, installed: 1.13.0]
  - astor [required: >=0.6.0, installed: 0.8.1]
  - backports.weakref [required: >=1.0rc1, installed: 1.0.post1]
  - enum34 [required: >=1.1.6, installed: 1.1.6]
  - functools32 [required: >=3.2.3, installed: 3.2.3.post2]
  - gast [required: ==0.2.2, installed: 0.2.2]
  - google-pasta [required: >=0.1.8, installed: 0.1.8]
    - six [required: Any, installed: 1.13.0]
  - grpcio [required: >=1.8.6, installed: 1.25.0]
    - enum34 [required: >=1.0.4, installed: 1.1.6]
    - futures [required: >=2.2.0, installed: 3.3.0]
    - six [required: >=1.5.2, installed: 1.13.0]
  - keras-applications [required: >=1.0.8, installed: 1.0.8]
    - h5py [required: Any, installed: 2.10.0]
      - numpy [required: >=1.7, installed: 1.16.5]
      - six [required: Any, installed: 1.13.0]
    - numpy [required: >=1.9.1, installed: 1.16.5]
  - keras-preprocessing [required: >=1.1.0, installed: 1.1.0]
    - numpy [required: >=1.9.1, installed: 1.16.5]
    - six [required: >=1.9.0, installed: 1.13.0]
  - mock [required: >=2.0.0, installed: 3.0.5]
    - funcsigs [required: >=1, installed: 1.0.2]
    - six [required: Any, installed: 1.13.0]
  - numpy [required: >=1.16.0,<2.0, installed: 1.16.5]
  - opt-einsum [required: >=2.3.2, installed: 2.3.2]
    - numpy [required: >=1.7, installed: 1.16.5]
  - protobuf [required: >=3.8.0, installed: 3.11.1]
    - setuptools [required: Any, installed: 42.0.2]
    - six [required: >=1.9, installed: 1.13.0]
  - six [required: >=1.12.0, installed: 1.13.0]
  - tb-nightly [required: >=2.1.0a0,<2.2.0a0, installed: 2.1.0a20191206]
    - absl-py [required: >=0.4, installed: 0.8.1]
      - enum34 [required: Any, installed: 1.1.6]
      - six [required: Any, installed: 1.13.0]
    - futures [required: >=3.1.1, installed: 3.3.0]
    - google-auth [required: >=1.6.3,<2, installed: 1.8.2]
      - cachetools [required: >=2.0.0,<3.2, installed: 3.1.1]
      - pyasn1-modules [required: >=0.2.1, installed: 0.2.7]
        - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
      - rsa [required: >=3.1.4,<4.1, installed: 4.0]
        - pyasn1 [required: >=0.1.3, installed: 0.4.8]
      - setuptools [required: >=40.3.0, installed: 42.0.2]
      - six [required: >=1.9.0, installed: 1.13.0]
    - google-auth-oauthlib [required: >=0.4.1,<0.5, installed: 0.4.1]
      - google-auth [required: Any, installed: 1.8.2]
        - cachetools [required: >=2.0.0,<3.2, installed: 3.1.1]
        - pyasn1-modules [required: >=0.2.1, installed: 0.2.7]
          - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
        - rsa [required: >=3.1.4,<4.1, installed: 4.0]
          - pyasn1 [required: >=0.1.3, installed: 0.4.8]
        - setuptools [required: >=40.3.0, installed: 42.0.2]
        - six [required: >=1.9.0, installed: 1.13.0]
      - requests-oauthlib [required: >=0.7.0, installed: 1.3.0]
        - oauthlib [required: >=3.0.0, installed: 3.1.0]
        - requests [required: >=2.0.0, installed: 2.22.0]
          - certifi [required: >=2017.4.17, installed: 2019.11.28]
          - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
          - idna [required: >=2.5,<2.9, installed: 2.8]
          - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.7]
    - grpcio [required: >=1.24.3, installed: 1.25.0]
      - enum34 [required: >=1.0.4, installed: 1.1.6]
      - futures [required: >=2.2.0, installed: 3.3.0]
      - six [required: >=1.5.2, installed: 1.13.0]
    - markdown [required: >=2.6.8, installed: 3.1.1]
      - setuptools [required: >=36, installed: 42.0.2]
    - numpy [required: >=1.12.0, installed: 1.16.5]
    - protobuf [required: >=3.6.0, installed: 3.11.1]
      - setuptools [required: Any, installed: 42.0.2]
      - six [required: >=1.9, installed: 1.13.0]
    - requests [required: >=2.21.0,<3, installed: 2.22.0]
      - certifi [required: >=2017.4.17, installed: 2019.11.28]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.7]
    - setuptools [required: >=41.0.0, installed: 42.0.2]
    - six [required: >=1.10.0, installed: 1.13.0]
    - werkzeug [required: >=0.11.15, installed: 0.16.0]
    - wheel [required: Any, installed: 0.33.6]
  - termcolor [required: >=1.1.0, installed: 1.1.0]
  - tf-estimator-nightly [required: Any, installed: 2.0.0.dev2019121209]
  - wheel [required: Any, installed: 0.33.6]
  - wrapt [required: >=1.11.1, installed: 1.11.2]
tqdm==4.40.2
```

**Comment by brkygokcen** [comment]
@clemense Thank you for your reply. It really helped me and solved my issues. Thank you again.
